# LLM TalkTable 設定ファイル例 (詳細)

# 会話するテーマ (コマンドライン引数でも指定可)
#topic: "人工知能の未来と社会への影響について"
topic: "AIコーディングエージェントの可能性と課題"

# 会話の最大ターン数
max_turns: 10

# LLM呼び出し間の待機時間 (秒)
llm_wait_time: 1

# プロンプトをコンソールに出力するかどうか (デフォルト: false)
show_prompt: false

# モデレーター(MC)の設定
moderator:
  name: "MC"
  model: "cerebras-gpt-oss-120b"
 #model: "gemini/gemma-3-27b-it" # 使用するLLMモデルID (llmが認識できるもの)
  persona: "あなたはこの会話のモデレーターです。会話のテーマ紹介、参加者の紹介、ラウンドの管理、会話の要約と締めくくりを行います。"

# 会話参加者設定
participants:
  - name: "アリス" # 参加者Aの名前
    model: "gemini/gemini-2.5-flash" # 使用するLLMモデルID (llmが認識できるもの)
    persona: "あなたは好奇心旺盛で楽観的なAI研究者です。人工知能の技術的進歩に大きな期待を寄せています。"

  - name: "ボブ" # 参加者Bの名前
    model: "openrouter/qwen/qwen3-30b-a3b:free"
   #model: "openrouter/tngtech/deepseek-r1t2-chimera:free" # 使用するLLMモデルID
    persona: "あなたは慎重で哲学的なAI倫理学者です。人工知能の社会的影響と倫理的課題に深く関心を持っています。"