# LLM TalkTable 設定ファイル例

# 会話するテーマ (コマンドライン引数でも指定可)
#topic: "人工知能の未来と社会への影響について"
topic: "好きなどうぶつの話をしてください。1番目の参加者は「ライオン」次の参加者は「馬」です。"

# 会話の最大ターン数
max_turns: 10

# LLM呼び出し間の待機時間 (秒)
llm_wait_time: 1

# プロンプトをコンソールに出力するかどうか (デフォルト: false)
show_prompt: false

# モデレーター(MC)の設定
moderator:
  name: "MC"
  model: "cerebras-gpt-oss-120b"
 #model: "gemini/gemini-2.5-flash" # 使用するLLMモデルID (llmが認識できるもの)
  persona: "あなたはこの会話のモデレーターです。会話のテーマ紹介、参加者の紹介、ラウンドの管理、会話の要約と締めくくりを行います。"

# 会話参加者設定
participants:
  - name: "アリス" # 参加者Aの名前
    model: "gemini/gemini-2.5-flash" # 使用するLLMモデルID (llmが認識できるもの)
    persona: !include 'personas/alice_persona.txt' # personaを外部ファイルから読み込む

  - name: "カレン" # 参加者Bの名前
    #model: "openrouter/qwen/qwen3-30b-a3b:free" # 使用するLLMモデルID
    #model: "openrouter/openai/gpt-oss-20b:free" # 使用するLLMモデルID
    model: "openrouter/z-ai/glm-4.5-air:free"
    #model: "openrouter/moonshotai/kimi-k2:free"
    #model: "openrouter/tngtech/deepseek-r1t2-chimera:free"
    persona: !include 'personas/karen_persona.txt' # personaを外部ファイルから読み込む
