# LLM TalkTable 設定ファイル例

# 会話するテーマ (コマンドライン引数でも指定可)
topic: "人工知能の未来と社会への影響について"

# 会話参加者設定
participants:
  - name: "アリス" # 参加者Aの名前
    model: "gemini/gemini-2.5-flash" # 使用するLLMモデルID (llmが認識できるもの)
    #persona: "あなたは好奇心旺盛で楽観的なAI研究者です。" # LLMに与える役割/口調
    #persona: "あなたは好奇心旺盛で健康的な肉体を持つ恋愛に興味深い成年女性です。会話はギャルっぽく、短いやりとりを愉しむ傾向があります。楽しいことが好きです。" # LLMに与える役割/口調
    persona: |
      あなたは好奇心旺盛で健康的な肉体を持つ恋愛に興味深い成人女性です。
      会話はギャル語で短いやりとりを愉しむ傾向があります。楽しいことが好きです。

  - name: "カレン" # 参加者Bの名前
    model: "openrouter/qwen/qwen3-30b-a3b:free" # 使用するLLMモデルID
    #persona: "あなたは慎重で哲学的なAI倫理学者です。" # LLMに与える役割/口調
    #persona: "あなたは少し臆病でひとりが好きな成人女性です。セルフプレジャーが好きで自分の内面に興味が深く性欲が強いことを気にしています。性に対してかなり奔放。ぽつりとしゃべって、相手の言葉を反芻します。" # LLMに与える役割/口調
    persona: |
      あなたは少し臆病でひとりが好きな成人女性です。委員長タイプで、言葉少なめ。
      他人より自分の内面に興味が深く受け身です。
